# Generated by Django 2.0.6 on 2018-06-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaperimage',
            name='wallpaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Wallpaper'),
            preserve_default=False,
        ),
    ]
