# Generated by Django 2.0.6 on 2018-06-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_wallpaperimage_wallpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaperimage',
            name='title',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
