# Generated by Django 2.0.6 on 2018-06-25 21:47

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180625_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last visited'),
        ),
        migrations.AlterField(
            model_name='wallpaperimage',
            name='img',
            field=models.ImageField(upload_to=event.models.get_file_path, verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='wallpaperimage',
            name='wallpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpaper_images', to='event.Wallpaper'),
        ),
    ]
