# Generated by Django 2.0.6 on 2018-06-26 19:25

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180625_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='cert',
            field=models.ImageField(default='', upload_to=event.models.get_file_path, verbose_name='Certificate file'),
            preserve_default=False,
        ),
    ]
