# Generated by Django 2.0.6 on 2018-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_wallpaper_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='last_visit',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last visited'),
        ),
        migrations.AlterField(
            model_name='wallpaperimage',
            name='device',
            field=models.CharField(choices=[('hd', 'HD'), ('uhd', 'UHD'), ('iphone', 'iPhone 6/7/8'), ('iphoneplus', 'iPhone 6+/7+/8+'), ('iphonex', 'iPhone X'), ('samsung', 'Samsung S8/S8 Plus or S9/S9 Plus')], max_length=12, verbose_name='Target device'),
        ),
    ]
