# Generated by Django 2.0.6 on 2018-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presaleorder',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('btc', 'BTC'), ('eth', 'ETH')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='presaleorder',
            name='investor_type',
            field=models.CharField(choices=[('individual', 'Individual person'), ('investor', 'Accreditated investor'), ('fund', 'Fund')], max_length=11, verbose_name='Investor type'),
        ),
    ]
